### ISSUE TITLE
Palabras no permitidas

### ISSUE THREAD

**Issue by dariwonka** [Kukident/Forocoches_Hide_Beta#12]
No deja guardar palabras como rocoso, real madrid, podemos...

**Comment by Kukident** [comment]
¿Podrías pasarme tu lista de palabras actual a ver si consigo replicar yo el error?

El problema puede ser debido a tener una lista muy grande de palabras, o que haya algún carácter raro que a veces se le atraganta

**Comment by dariwonka** [comment]
Acabao de mirar y ya les tenia metidas, por eso se borraban automaticamente 🤦‍♂️
